# リリース用

name: For release

on:
  # releaseブランチへのプッシュをトリガー対象とする
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Create temp branch
        id: create_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
        run: |
          DATE=`date +"%Y%m%d"`
          BRANCH_NAME="for_release_$DATE"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          echo ::set-output name=branch_name::$BRANCH_NAME
      
      - name: Create pull request
        env:
          REVIEWERS: "kuyuri-iroha"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        run: |
          DATE=`date +"%Y%m%d"`
          hub pull-request -m "Release $DATE" -b master -h $BRANCH_NAME -l "PR:draft" -r "$REVIEWERS"
